version: "3.8"

services: 
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crtest
      POSTGRES_USER: crtest
      POSTGRES_PASSWORD: crtest
    expose:
      - 5432
  rabbitmq:
    build:
      context: rabbitmq
    container_name: rabbitmq
    hostname: cr-broker
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: crtest
      RABBITMQ_DEFAULT_PASS: crtest
  django:
    build:
      context: .
      target: ci-django
    container_name: django
    environment:
      DJANGO_SECRET: secret
      DJANGO_DEBUG: 1
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE: postgres
      POSTGRES_DB: crtest
      POSTGRES_USER: crtest
      POSTGRES_PASSWORD: crtest
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: crtest
      RABBITMQ_PASS: crtest
      MQTT_BROKER_HOST: rabbitmq
      MQTT_BROKER_MANAGEMENT_PORT: 15672
      MQTT_BROKER_PORT: 1883
      MQTT_BROKER_USERNAME: crtest
      MQTT_BROKER_PASSWORD: crtest
    restart: unless-stopped
    volumes:
      - ./:/opt/app
    depends_on: 
      - postgres
      - rabbitmq
