version: "3.7"

services: 
  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    env_file: ./cloudroom/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes: 
      - redis_data:/data
    expose:
      - 6379
  django:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/usr/app
      - static_files:/usr/app/static
      - media_files:/usr/app/media
    env_file: ./cloudroom/.env
    restart: unless-stopped
    command: [python, manage.py, runserver, 0.0.0.0:8000]
    # command: [daphne, -b, "0.0.0.0", -p, "8000", cloudroom.asgi:application]
    entrypoint: [/usr/app/entrypoint.sh]
    ports: 
      - 8000:8000
    depends_on: 
      - postgres
      - redis
  celery_worker:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/usr/app
      - static_files:/usr/app/static
      - media_files:/usr/app/media
    env_file: ./cloudroom/.env
    restart: unless-stopped
    command: [celery, -A, cloudroom, worker, -l, INFO]
    depends_on: 
      - postgres
      - redis
  celery_beat:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/usr/app
      - static_files:/usr/app/static
      - media_files:/usr/app/media
    env_file: ./cloudroom/.env
    restart: unless-stopped
    command: [celery, -A, cloudroom, beat, -l, INFO]
    depends_on: 
      - postgres
      - redis
  # vosk:
  #   image: gabrielbg99/kaldi-en
  #   restart: unless-stopped
  #   expose:
  #     - 2700
volumes: 
  postgres_data:
  redis_data:
  static_files:
  media_files:
