version: "3"

services: 
  postgres:
    image: postgres:12-alpine
    restart: always
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
  django:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/home/app
    env_file: ./.env
    restart: always
    command: >
      sh -c "
        python manage.py migrate && \
        python manage.py runserver 0.0.0.0:8000"
    ports: 
      - 8000:8000
    depends_on: 
      - postgres
      - redis
  celery_worker:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/home/app
    env_file: ./.env
    restart: always
    command: [celery, -A, cloudroom, worker, -l, info]
    depends_on: 
      - postgres
      - redis
  celery_beat:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/home/app
    env_file: ./.env
    restart: always
    command: [celery, -A, cloudroom, beat, -l, info]
    depends_on: 
      - postgres
      - redis
volumes: 
  postgres_data: