version: "3.7"


services: 
  postgres:
    image: postgres:12-alpine
    restart: always
    env_file: ./cloudroom/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  redis:
    image: redis:5-alpine
    restart: always
    volumes: 
      - redis_data:/data
    expose:
      - 6379
  django:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/usr/app
    env_file: ./cloudroom/.env
    restart: always
    command: [python, manage.py, runserver, 0.0.0.0:8000]
    entrypoint: [/usr/app/entrypoint.sh]
    ports: 
      - 8000:8000
    depends_on: 
      - postgres
      - redis
  celery_worker:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/usr/app
    env_file: ./cloudroom/.env
    restart: always
    command: [celery, -A, cloudroom, worker, -l, INFO]
    depends_on: 
      - postgres
      - redis
  celery_beat:
    build: ./cloudroom
    volumes: 
      - ./cloudroom:/usr/app
    env_file: ./cloudroom/.env
    restart: always
    command: [celery, -A, cloudroom, beat, -l, INFO]
    depends_on: 
      - postgres
      - redis
volumes: 
  postgres_data:
  redis_data:
