version: "3.8"

services: 
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  rabbitmq:
    build:
      context: rabbitmq
    container_name: rabbitmq
    hostname: cr-broker
    restart: unless-stopped
    env_file: ./rabbitmq/.env
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 1883:1883
  django:
    build:
      context: .
      target: django
    container_name: django
    volumes: 
      - ./:/opt/app
      - static_files:/opt/app/static
      - media_files:/opt/app/media
    env_file: ./.env
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on: 
      - postgres
      - rabbitmq
  celery_worker:
    build:
      context: .
      target: celery-worker
    container_name: celery_worker
    volumes: 
      - ./:/opt/app
      - static_files:/opt/app/static
      - media_files:/opt/app/media
    env_file: ./.env
    restart: unless-stopped
    depends_on: 
      - postgres
      - rabbitmq
  celery_beat:
    build:
      context: .
      target: celery-beat
    container_name: celery_beat
    volumes: 
      - ./:/opt/app
      - static_files:/opt/app/static
      - media_files:/opt/app/media
    env_file: ./.env
    restart: unless-stopped
    depends_on: 
      - postgres
      - rabbitmq
volumes: 
  postgres_data:
  rabbitmq_data:
  static_files:
  media_files:
