version: "3.8"

services: 
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    expose:
      - 5432
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
  django:
    build:
      context: .
      target: django
    container_name: django
    environment:
      - DJANGO_SECRET
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - REDIS_HOST
      - REDIS_PORT
      - MQTT_BROKER_HOST
      - MQTT_BROKER_MANAGEMENT_PORT
      - MQTT_BROKER_PORT
      - MQTT_BROKER_USERNAME
      - MQTT_BROKER_PASSWORD
    restart: unless-stopped
    volumes:
      - ./:/opt/app
    depends_on: 
      - postgres
      - redis
