version: "3.8"

services: 
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes: 
      - redis_data:/data
    expose:
      - 6379
  django:
    build:
      context: .
      target: django
    container_name: django
    volumes: 
      - ./:/opt/app
      - static_files:/opt/app/static
      - media_files:/opt/app/media
    env_file: ./.env
    restart: unless-stopped
    ports: 
      - 8000:8000
    depends_on: 
      - postgres
      - redis
  celery_worker:
    build:
      context: .
      target: base
    container_name: celery_worker
    volumes: 
      - ./:/opt/app
      - static_files:/opt/app/static
      - media_files:/opt/app/media
    env_file: ./.env
    restart: unless-stopped
    command: [celery, -A, cloudroom, worker, -l, INFO]
    depends_on: 
      - postgres
      - redis
  celery_beat:
    build:
      context: .
      target: base
    container_name: celery_beat
    volumes: 
      - ./:/opt/app
      - static_files:/opt/app/static
      - media_files:/opt/app/media
    env_file: ./.env
    restart: unless-stopped
    command: [celery, -A, cloudroom, beat, -l, INFO]
    depends_on: 
      - postgres
      - redis
volumes: 
  postgres_data:
  redis_data:
  static_files:
  media_files:
